name: Check Application One
on:
  push:
    branches:
      - master

jobs:
  validate:
    name: Greeting from branch
    runs-on: ubuntu-latest
    steps:
      - name: Checking out sources
        uses: actions/checkout@v2
