name: Validate application
description: GitHub Action that runs linting, testing and type checking on target application

inputs:
  application:
    description: 'Application to validate'
    required: true

outputs:
  time:
    description: 'The time we greeted you'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.application }}

