name: Check Application One
on:
  push:
    paths:
      - 'apps/app1/**'
      - '!packages/**'

jobs:
  validate:
    name: Building application one
    runs-on: ubuntu-latest
    steps:
      - name: Greet application one
        run: echo '${{ toJSON(github) }}'

