name: Check Application Two
on:
  push:
    branches:
      - master
    paths:
      - 'apps/app2/**'

jobs:
  validate:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Greet application two
        run: echo 'Hello from application two'

