name: Check Application One
on:
  push:
    paths:
      - '!packages/**'
      - 'apps/app1/**'

jobs:
  validate:
    name: Building application one
    runs-on: ubuntu-latest
    steps:
      - name: Greet application one
        run: echo 'Hello from application one'

