name: Check Application One
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Checking out sources
        uses: actions/checkout@v2

#      - name: Setting up node
#        uses: actions/setup-node@v1
#        with:
#          node-version: '12.x'
#
#      - name: Installing dependencies
#        run: yarn --frozen-lockfile

      - name: SHA
        run: echo "${{ github.sha[0..6] }}"

      - name: Event
        run: echo "${{ toJSON(github.event) }}"

      - name: Event name
        run: echo "${{ github.event_name }}"

      - name: Hello world action step
        uses: ./.github/actions/validate-application # Uses an action in the root directory
        id: hello
        with:
          application: '@monorepo/app1'
          who-to-greet: 'Mona the Octocat'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

