name: Pingwin Pull Request
on:
  [push]

env:
  NAMESPACE: pingwin
  ECR_HOST: 616837500225.dkr.ecr.us-east-1.amazonaws.com
  IMAGE_NAME: $ECR_HOST/pingwin/pingwin-fe

jobs:
  verify:
    name: Verify Pingwin is ready to be merged
    runs-on: ubuntu-latest
    steps:
#      - name: Checking out sources
#        uses: actions/checkout@v2

      - run: echo $DOCKER_REGISTRY
      - run: echo $NAMESPACE

      #      - name: Setting up node
      #        uses: actions/setup-node@v1
      #        with:
      #          node-version: '12.x'
      #
      #       todo: remove dat installation
      #      - name: Installing yarn
      #        run: curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | echo '' | sudo tee /etc/yum.repos.d/yarn.repo
      #      - run: sudo yum install yarn
      #
      #      - name: Installing dependencies
      #        run: yarn install --frozen-lockfile
      #
      #      - name: Testing
      #        run: yarn workspace @lyft/pingwin test
      #
      #      - name: Linting
      #        run: yarn ci:lint
      #
      #      - name: Type checking
      #        run: yarn ci:tsc

#      - name: Echoing
#        env:
#          SUPER_SECRET: ${{ secrets.ECR_HOST }}
#        run: echo "$SUPER_SECRET"


#      - name: Building image
#        run: docker build -t $IMAGE_NAME:${GITHUB_SHA::8} -f apps/pingwin/Dockerfile .

#      - name: Pushing image
#        run:

#      - name: Cleaning
#        run:

#      - name: Sending successful message
