name: Pingwin Pull Request
on:
  [pull_request]

jobs:
  verify1:
    name: Verify application one is ready to be merged
    runs-on: ubuntu-latest
    steps:
      - name: Checking out sources
        uses: actions/checkout@v2

      - name: Setting up node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Testing
        run: yarn workspace @monorepo/app1 test

  verify2:
    name: Verify application two is ready to be merged
    runs-on: ubuntu-latest
    steps:
      - name: Checking out sources
        uses: actions/checkout@v2

      - name: Setting up node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Testing
        run: yarn workspace @monorepo/app2 test
